### ISSUE TITLE
conda-env.txt missing

### ISSUE THREAD

**Issue by youngstudent2** [rizwan09/REDCODER#2]
dear author,

when I tried to install SCODE-G , running `bash install_tools.sh`,  there is something wrong:
```
+ REPO=/mnt/d/github/REDCODER/SCODE-G
+ LIB=/mnt/d/github/REDCODER/SCODE-G/third_party
+ mkdir -p /mnt/d/github/REDCODER/SCODE-G/third_party
+ conda create --name plbart --file conda-env.txt

CondaFileIOError: 'conda-env.txt'. [Errno 2] No such file or directory: 'conda-env.txt'
```

Could you please upload conda-env.txt?
Thanks!

**Comment by rizwan09** [comment]
Hi,
Thanks so much for your interest in Redcoder. Would it be possible for you to install the PLBART separately first? [Here](https://github.com/wasiahmad/PLBART) is the PLBART's page. PLBART is the Score-G module in Redcoder that has only differences on the input side.  And therefore after the installation of PLBART you can follow the other commands in Scode-G. 

Thanks, Please let me know if you come up with any other difficulties.

**Comment by youngstudent2** [comment]
Thank you for explaining! 😄
