### ISSUE TITLE
Where is the train and test files in SCODE-G

### ISSUE THREAD

**Issue by polangjushi** [rizwan09/REDCODER#8]
Dear authors,

As for the data related to part SCODE-G, I only found the test file ‘python_csnet_code_text_retrieval_dedup_valid_30.json’ on Google Web Disk, but no train or test files were found. I don't know where to download them.

**Comment by rizwan09** [comment]
Hi, many thanks for your interests. In case if you missed the readme, the link (the last link on that page) was provided there, 
Please find here: https://drive.google.com/drive/folders/1qrt6DkJKp43TNN_wCTVCP98BOtD-9o9J?usp=sharing. Look for the retriever output zip file in the shared directory.
